# Generated by Django 4.1.7 on 2023-04-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_ngo_restaurant_delete_customuser_delete_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='address',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ngo',
            name='description',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='ngo',
            name='email_id',
            field=models.EmailField(default=True, max_length=30),
        ),
        migrations.AddField(
            model_name='ngo',
            name='name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ngo',
            name='phone_number',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ngo',
            name='website',
            field=models.URLField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='email_id',
            field=models.EmailField(default=True, max_length=30),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.URLField(default=True),
        ),
    ]
