# Generated by Django 4.1.7 on 2023-04-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_ngo_address_ngo_description_ngo_email_id_ngo_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donator_name', models.CharField(max_length=255)),
                ('food_type', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('pickup_location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
