# Generated by Django 4.1.7 on 2023-04-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donator_name', models.CharField(max_length=255)),
                ('food_type', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('pickup_time', models.TimeField()),
                ('pickup_location', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
