# Generated by Django 4.1.7 on 2023-04-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
        migrations.AddField(
            model_name='donation',
            name='action',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
