# Generated by Django 4.1.7 on 2023-04-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_history_donation_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='action',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
